#include "SortGraphPinFactory.h"
#include "SGraphPinStructPropertyName.h"
#include "K2Node_SmartSort.h"
#include "EdGraphSchema_K2.h"

TSharedPtr<class SGraphPin> FSortGraphPinFactory::CreatePin(class UEdGraphPin* InPin) const
{
    if (!InPin)
    {
        return nullptr;
    }

    // 检查是否为智能排序节点的属性名称引脚
    if (InPin->PinType.PinCategory == UEdGraphSchema_K2::PC_Name &&
        InPin->PinName == FSmartSort_Helper::PN_PropertyName)
    {
        UK2Node_SmartSort* SmartSortNode = Cast<UK2Node_SmartSort>(InPin->GetOuter());
        if (SmartSortNode)
        {
            // 获取数组引脚
            UEdGraphPin* ArrayPin = SmartSortNode->FindPin(FSmartSort_Helper::PN_TargetArray);
            if (ArrayPin)
            {
                // 只检查结构体类型
                if (ArrayPin->PinType.PinCategory == UEdGraphSchema_K2::PC_Struct)
                {
                    // 获取结构体属性列表
                    TArray<FString> PropertyNames = SmartSortNode->GetAvailableProperties(ArrayPin->PinType);
                    return SNew(SGraphPinStructPropertyName, InPin, PropertyNames);
                }
                else
                {
                    // 对于非结构体类型，使用默认值
                    GetDefault<UEdGraphSchema_K2>()->SetPinAutogeneratedDefaultValueBasedOnType(InPin);
                }
            }
        }
    }

    return nullptr;
}
