// Copyright (c) 2024 Damian Nowakowski. All rights reserved.

#pragma once

#include "CoreMinimal.h"

/**
 * EnhancedCodeFlow 性能统计定义
 * 提供详细的运行时性能监控和调试信息
 */

#if STATS
// 主要统计组
DECLARE_STATS_GROUP(TEXT("ECF"), STATGROUP_ECF, STATCAT_Advanced);
DECLARE_STATS_GROUP(TEXT("ECFDetails"), STATGROUP_ECFDETAILS, STATCAT_Advanced);

// 核心统计项
DECLARE_DWORD_COUNTER_STAT_EXTERN(TEXT("Actions"), STAT_ECF_ActionsCount, STATGROUP_ECF, XTOOLS_ENHANCEDCODEFLOW_API);
DECLARE_DWORD_COUNTER_STAT_EXTERN(TEXT("Instances"), STAT_ECF_InstancesCount, STATGROUP_ECF, XTOOLS_ENHANCEDCODEFLOW_API);
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN(TEXT("Action Objects"), STAT_ECF_ActionsObjectsCount, STATGROUP_ECF, XTOOLS_ENHANCEDCODEFLOW_API);
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN(TEXT("Async BP Objects"), STAT_ECF_AsyncBPObjectsCount, STATGROUP_ECF, XTOOLS_ENHANCEDCODEFLOW_API);

// 详细统计项
DECLARE_DWORD_COUNTER_STAT_EXTERN(TEXT("Delay Actions"), STAT_ECF_DelayActionsCount, STATGROUP_ECFDETAILS, XTOOLS_ENHANCEDCODEFLOW_API);
DECLARE_DWORD_COUNTER_STAT_EXTERN(TEXT("Async Actions"), STAT_ECF_AsyncActionsCount, STATGROUP_ECFDETAILS, XTOOLS_ENHANCEDCODEFLOW_API);
DECLARE_DWORD_COUNTER_STAT_EXTERN(TEXT("Coroutine Actions"), STAT_ECF_CoroutineActionsCount, STATGROUP_ECFDETAILS, XTOOLS_ENHANCEDCODEFLOW_API);
DECLARE_FLOAT_ACCUMULATOR_STAT_EXTERN(TEXT("Average Action Duration"), STAT_ECF_AverageActionDuration, STATGROUP_ECFDETAILS, XTOOLS_ENHANCEDCODEFLOW_API);
#endif
