/*
 * Copyright (c) 2025 XIYBHK
 * Licensed under UE_XTools License
 * 
 * Based on AdvancedControlFlow by Colory Games (MIT License)
 * https://github.com/colory-games/UEPlugin-AdvancedControlFlow
 */

#include "K2Nodes/K2Node_MultiConditionalSelect.h"
#include "K2Nodes/K2NodeHelpers.h"

#include "BlueprintNodeSpawner.h"
#include "EditorCategoryUtils.h"
#include "GraphEditorSettings.h"
#include "K2Node_CallFunction.h"
#include "K2Node_MakeArray.h"
#include "K2Node_Select.h"
#include "Kismet/KismetArrayLibrary.h"
#include "Kismet/KismetMathLibrary.h"
#include "Kismet2/BlueprintEditorUtils.h"
#include "KismetCompiler.h"

#define LOCTEXT_NAMESPACE "BlueprintExtensions"

const FName DefaultOptionPinName(TEXT("Default"));
const FName ReturnValueOptionPinName(TEXT("Return Value"));
const FName OptionPinFriendlyNamePrefix(TEXT("Option "));
const FName ConditionPinFriendlyNamePrefix(TEXT("Condition "));

UK2Node_MultiConditionalSelect::UK2Node_MultiConditionalSelect(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
{
	NodeContextMenuSectionName = "K2NodeMultiConditionalSelect";
	NodeContextMenuSectionLabel = LOCTEXT("MultiConditionalSelect", "多条件选择");
	CaseKeyPinNamePrefix = TEXT("CaseOption");
	CaseValuePinNamePrefix = TEXT("CaseCondition");
	CaseKeyPinFriendlyNamePrefix = TEXT("Option ");
	CaseValuePinFriendlyNamePrefix = TEXT("Condition ");
}

void UK2Node_MultiConditionalSelect::AllocateDefaultPins()
{
	// Pin structure
	//   N: Number of option/condition pin pair
	// -----
	// 0: Default (In, Wildcard)
	// 1-N: Option (In, Wildcard)
	// (N+1)-2N: Condition (In, Boolean)
	// 2N+1: Return Value (Out, Boolean)

	CreateDefaultOptionPin();
	CreateReturnValuePin();

	for (int Index = 0; Index < 2; ++Index)
	{
		AddCasePinPair(Index);
	}

	Super::AllocateDefaultPins();
}

FText UK2Node_MultiConditionalSelect::GetTooltipText() const
{
	return LOCTEXT("MultiConditionalSelect_Tooltip", "多条件选择\n纯函数节点，返回第一个条件为 true 对应的选项值\n类似多条件的三元运算符 (condition ? value1 : value2)");
}

FLinearColor UK2Node_MultiConditionalSelect::GetNodeTitleColor() const
{
	return GetDefault<UGraphEditorSettings>()->PureFunctionCallNodeTitleColor;
}

FText UK2Node_MultiConditionalSelect::GetNodeTitle(ENodeTitleType::Type TitleType) const
{
	return LOCTEXT("MultiConditionalSelect", "多条件选择");
}

FSlateIcon UK2Node_MultiConditionalSelect::GetIconAndTint(FLinearColor& OutColor) const
{
	static FSlateIcon Icon("EditorStyle", "GraphEditor.Select_16x");
	return Icon;
}

void UK2Node_MultiConditionalSelect::PinConnectionListChanged(UEdGraphPin* Pin)
{
	if (Pin == nullptr)
	{
		return;
	}
	Super::PinConnectionListChanged(Pin);

	if (Pin->LinkedTo.Num() == 0)
	{
		// Ignore the disconnection event.
		return;
	}

	if (IsCaseValuePin(Pin))
	{
		// Ignore condition pin connection.
		return;
	}

	if (GetDefaultOptionPin()->PinType.PinCategory != UEdGraphSchema_K2::PC_Wildcard)
	{
		// Pin type has already fixed.
		return;
	}

	Modify();

	const UEdGraphSchema_K2* Schema = GetDefault<UEdGraphSchema_K2>();
	UEdGraphPin* LinkedPin = Pin->LinkedTo[0];

	UEdGraphPin* DefaultOptionPin = GetDefaultOptionPin();
	DefaultOptionPin->PinType = LinkedPin->PinType;
	Schema->ResetPinToAutogeneratedDefaultValue(DefaultOptionPin);

	UEdGraphPin* ReturnValuePin = GetReturnValuePin();
	ReturnValuePin->PinType = LinkedPin->PinType;
	Schema->ResetPinToAutogeneratedDefaultValue(ReturnValuePin);

	TArray<CasePinPair> CasePinPairs = GetCasePinPairs();
	for (auto& Pair : CasePinPairs)
	{
		UEdGraphPin* OptionPin = Pair.Key;

		OptionPin->PinType = LinkedPin->PinType;
		Schema->ResetPinToAutogeneratedDefaultValue(OptionPin);
	}

	if (UBlueprint* Blueprint = FBlueprintEditorUtils::FindBlueprintForNode(this))
	{
		FBlueprintEditorUtils::MarkBlueprintAsModified(Blueprint);
		Blueprint->BroadcastChanged();
	}
}

void UK2Node_MultiConditionalSelect::ReallocatePinsDuringReconstruction(TArray<UEdGraphPin*>& OldPins)
{
	UEdGraphPin* OldDefaultPin = nullptr;
	for (auto& Pin : OldPins)
	{
		if (Pin->GetFName() == DefaultOptionPinName)
		{
			OldDefaultPin = Pin;
		}
	}

	CreateDefaultOptionPin();
	CreateReturnValuePin();
	Super::ReallocatePinsDuringReconstruction(OldPins);

	if (OldDefaultPin != nullptr)
	{
		GetDefaultOptionPin()->PinType = OldDefaultPin->PinType;
		GetReturnValuePin()->PinType = OldDefaultPin->PinType;
		for (auto& Pair : GetCasePinPairs())
		{
			Pair.Key->PinType = OldDefaultPin->PinType;
		}
	}
}

void UK2Node_MultiConditionalSelect::GetMenuActions(FBlueprintActionDatabaseRegistrar& ActionRegistrar) const
{
	K2NodeHelpers::RegisterNode<UK2Node_MultiConditionalSelect>(ActionRegistrar);
}

FText UK2Node_MultiConditionalSelect::GetMenuCategory() const
{
	return FEditorCategoryUtils::GetCommonCategory(FCommonEditorCategory::Utilities);
}

// clang-format off
/*
* Internal node structure

            +-----------------------------------------------------------------------------------------------------------------------+
            |                                                                                                                       |
            |                                         +----------------------------+           +----------------------------+       |
            |                                         |          Select            |           |           Select           |       |
            |                                         |                            |           |                            |       |
            +-+                                       +-+                        +-+           +-+                        +-+     +-+
   Option 0 | +---------------------------------------+ | Option 0  Return Value | +-----------+ | False     Return Value | +-----+ | Return Value
            +-+                                       +-+                        +-+           +-+                        +-+     +-+
            |                                         |                            |           |                            |       |
            |                                         |                            |           |                            |       |
            +-+                                       +-+                          |           +-+                          |       |
   Option 1 | +---------------------------------------+ | Option 1                 |   +-------+ | True                     |       |
            +-+                                       +-+                          |   |       +-+                          |       |
            |                                         |                            |   |       |                            |       |
            |                                         |                            |   |       |                            |       |
            +-+                                       +-+                          |   |       +-+                          |       |
    Default | +------------------+            +-------+ | Index (Integer)          |   |    +--+ | Index (Boolean)          |       |
            +-+                  |            |       +-+                          |   |    |  +-+                          |       |
            |                    |            |       |                            |   |    |  |                            |       |
            |                    |            |       |                            |   |    |  |                            |       |
            |                    |            |       +----------------------------+   |    |  +----------------------------+       |
            |                    |            x                                        |    |                                       |
            |                    |            x                                        |    |                                       |
            |                    +------------x----------------------------------------+    +------------------------+              |
            |                                 x                                                                      |              |
            |                                 x-----------------------------------+                                  |              |
            |                                                                     |                                  |              |
            |       +------------------+     +---------------------------------+  |  +-----------------------+       |              |
            |       |    Make Array    |     |          Find (Array)           |  |  |     == (Integer)      |       |              |
            |       |                  |     |                                 |  |  |                       |       |              |
            +-+     +-+              +-+     +-+                             +-+  |  +-+                   +-+       |              |
Condition 0 | +-----+ | [0]    Array | +-----+ | Target Array   Return Value | +--+--+ | A    Return Value | +-------+              |
            +-+     +-+              +-+     +-+                             +-+     +-+                   +-+                      |
            |       |                  |     |                                 |     |                       |                      |
            |       |                  |     |                                 |     |                       |                      |
            +-+     +-+                |     +-+                               |     +-+                     |                      |
Condition 1 | +-----+ | [1]            |     | | Item To Find                  |     | | B                   |                      |
            +-+     +-+                |     +-+                               |     +-+                     |                      |
            |       |                  |     |                                 |     |                       |                      |
            |       |                  |     |                                 |     |                       |                      |
            |       +------------------+     +---------------------------------+     +-----------------------+                      |
            |                                                                                                                       |
            |                                                                                                                       |
            +-----------------------------------------------------------------------------------------------------------------------+
 */
// clang-format on
void UK2Node_MultiConditionalSelect::ExpandNode(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph)
{
	// 先展开拆分引脚：结构体引脚被分割（Split Struct Pin）后链接挂在子引脚上，
	// 不展开则 MovePinLinksToIntermediate 迁移不到链接，下游会静默读到默认值
	Super::ExpandNode(CompilerContext, SourceGraph);

	// 直接构建中间节点，并在完成引脚迁移后显式断开原节点链接。

	TArray<CasePinPair> CasePinPairs = GetCasePinPairs();
	UEdGraphPin* DefaultOptionPin = GetDefaultOptionPin();
	UEdGraphPin* ReturnValuePin = GetReturnValuePin();
	if (CasePinPairs.Num() == 0 || !DefaultOptionPin || !ReturnValuePin)
	{
		K2NodeHelpers::ReportExpandError(
			CompilerContext,
			this,
			LOCTEXT("MultiConditionalSelect_InvalidPins", "Multi Conditional Select node has invalid pins @@"));
		return;
	}
	for (const CasePinPair& Pair : CasePinPairs)
	{
		if (!Pair.Key || !Pair.Value)
		{
			K2NodeHelpers::ReportExpandError(
				CompilerContext,
				this,
				LOCTEXT("MultiConditionalSelect_InvalidCasePins", "Multi Conditional Select node has invalid case pins @@"));
			return;
		}
	}

	UEdGraphPin* ReferenceOptionPin = CasePinPairs[0].Key;
	if (ReferenceOptionPin->PinType.PinCategory == UEdGraphSchema_K2::PC_Wildcard)
	{
		K2NodeHelpers::ReportExpandError(
			CompilerContext,
			this,
			LOCTEXT("MultiConditionalSelect_UnresolvedType", "Multi Conditional Select node has an unresolved option type @@"));
		return;
	}

	UFunction* ArrayFindFunction = UKismetArrayLibrary::StaticClass()->FindFunctionByName(
		GET_FUNCTION_NAME_CHECKED(UKismetArrayLibrary, Array_Find));
	UFunction* EqualEqualIntIntFunction = UKismetMathLibrary::StaticClass()->FindFunctionByName(
		GET_FUNCTION_NAME_CHECKED(UKismetMathLibrary, EqualEqual_IntInt));
	if (!ArrayFindFunction || !EqualEqualIntIntFunction)
	{
		K2NodeHelpers::ReportExpandError(
			CompilerContext,
			this,
			LOCTEXT("MultiConditionalSelect_MissingFunctions", "Multi Conditional Select node failed to resolve engine functions @@"));
		return;
	}

	UK2Node_Select* Select1st = CompilerContext.SpawnIntermediateNode<UK2Node_Select>(this, SourceGraph);
	Select1st->AllocateDefaultPins();
	Select1st->ChangePinType(ReferenceOptionPin);
	for (int32 Index = 2; Index < CasePinPairs.Num(); ++Index)
	{
		Select1st->AddInputPin();
	}

	UK2Node_Select* Select2nd = CompilerContext.SpawnIntermediateNode<UK2Node_Select>(this, SourceGraph);
	Select2nd->AllocateDefaultPins();
	Select2nd->ChangePinType(ReferenceOptionPin);
	for (int32 Index = 2; Index < CasePinPairs.Num(); ++Index)
	{
		Select2nd->AddInputPin();
	}

	UK2Node_MakeArray* MakeArray = CompilerContext.SpawnIntermediateNode<UK2Node_MakeArray>(this, SourceGraph);
	MakeArray->AllocateDefaultPins();
	for (int32 Index = 1; Index < CasePinPairs.Num(); ++Index)
	{
		MakeArray->AddInputPin();
	}

	UK2Node_CallFunction* ArrayFind = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
	ArrayFind->SetFromFunction(ArrayFindFunction);
	ArrayFind->AllocateDefaultPins();

	UK2Node_CallFunction* IntEqual = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
	IntEqual->SetFromFunction(EqualEqualIntIntFunction);
	IntEqual->AllocateDefaultPins();

	TArray<UEdGraphPin*> Select1stOptionPins;
	Select1st->GetOptionPins(Select1stOptionPins);
	TArray<UEdGraphPin*> KeyPins;
	TArray<UEdGraphPin*> ValuePins;
	MakeArray->GetKeyAndValuePins(KeyPins, ValuePins);
	UEdGraphPin* ArrayPin = MakeArray->GetOutputPin();
	UEdGraphPin* TargetArrayPin = ArrayFind->FindPin(TEXT("TargetArray"), EGPD_Input);
	UEdGraphPin* ItemToFindPin = ArrayFind->FindPin(TEXT("ItemToFind"), EGPD_Input);
	UEdGraphPin* ArrayFindOutputPin = ArrayFind->GetReturnValuePin();
	UEdGraphPin* Select1stIndexPin = Select1st->GetIndexPin();
	UEdGraphPin* IntEqualAPin = IntEqual->FindPin(TEXT("A"), EGPD_Input);
	UEdGraphPin* IntEqualBPin = IntEqual->FindPin(TEXT("B"), EGPD_Input);
	UEdGraphPin* Select1stReturnValuePin = Select1st->GetReturnValuePin();
	UEdGraphPin* IntEqualReturnValuePin = IntEqual->GetReturnValuePin();
	UEdGraphPin* Select2ndIndexPin = Select2nd->GetIndexPin();
	TArray<UEdGraphPin*> Select2ndOptionPins;
	Select2nd->GetOptionPins(Select2ndOptionPins);
	UEdGraphPin* Select2ndReturnValuePin = Select2nd->GetReturnValuePin();

	if (Select1stOptionPins.Num() < CasePinPairs.Num() || KeyPins.Num() < CasePinPairs.Num() || Select2ndOptionPins.Num() < 2 ||
		!K2NodeHelpers::BeginExpandNode(
			CompilerContext,
			this,
			{ArrayPin, TargetArrayPin, ItemToFindPin, ArrayFindOutputPin, Select1stIndexPin, IntEqualAPin, IntEqualBPin,
			 Select1stReturnValuePin, IntEqualReturnValuePin, Select2ndIndexPin, Select2ndReturnValuePin},
			LOCTEXT("MultiConditionalSelect_InvalidIntermediatePins", "Multi Conditional Select failed to allocate its intermediate pins @@")))
	{
		if (Select1stOptionPins.Num() < CasePinPairs.Num() || KeyPins.Num() < CasePinPairs.Num() || Select2ndOptionPins.Num() < 2)
		{
			K2NodeHelpers::ReportExpandError(
				CompilerContext,
				this,
				LOCTEXT("MultiConditionalSelect_InvalidIntermediatePinCounts", "Multi Conditional Select allocated an invalid number of intermediate pins @@"));
		}
		return;
	}

	// Link between outer and 1st Select
	for (int Index = 0; Index < CasePinPairs.Num(); ++Index)
	{
		CompilerContext.MovePinLinksToIntermediate(*CasePinPairs[Index].Key, *Select1stOptionPins[Index]);
	}

	// Link between outer and Make Array
	for (int Index = 0; Index < CasePinPairs.Num(); ++Index)
	{
		KeyPins[Index]->PinType.PinCategory = UEdGraphSchema_K2::PC_Boolean;
		CompilerContext.MovePinLinksToIntermediate(*CasePinPairs[Index].Value, *KeyPins[Index]);
	}

	// Link between Make Array and Array Find
	ArrayPin->PinType.PinCategory = UEdGraphSchema_K2::PC_Boolean;
	if (!K2NodeHelpers::TryConnect(CompilerContext, ArrayPin, TargetArrayPin))
	{
		K2NodeHelpers::EndExpandNode(this);
		return;
	}
	TargetArrayPin->PinType.PinCategory = UEdGraphSchema_K2::PC_Boolean;
	ItemToFindPin->PinType.PinCategory = UEdGraphSchema_K2::PC_Boolean;
	MakeArray->GetSchema()->TrySetDefaultValue(*ItemToFindPin, TEXT("true"));

	// Link between Array Find and 1st Select
	if (!K2NodeHelpers::TryConnect(CompilerContext, ArrayFindOutputPin, Select1stIndexPin))
	{
		K2NodeHelpers::EndExpandNode(this);
		return;
	}
	Select1st->NotifyPinConnectionListChanged(Select1stIndexPin);

	// Link between Array Find and Int Equal
	if (!K2NodeHelpers::TryConnect(CompilerContext, ArrayFindOutputPin, IntEqualAPin))
	{
		K2NodeHelpers::EndExpandNode(this);
		return;
	}
	ArrayFindOutputPin->GetSchema()->TrySetDefaultValue(*IntEqualBPin, TEXT("-1"));

	// Link among 1st Select, 2nd Select and Int Equal
	if (!K2NodeHelpers::TryConnect(CompilerContext, IntEqualReturnValuePin, Select2ndIndexPin))
	{
		K2NodeHelpers::EndExpandNode(this);
		return;
	}
	Select2nd->NotifyPinConnectionListChanged(Select2ndIndexPin);
	if (!K2NodeHelpers::TryConnect(CompilerContext, Select1stReturnValuePin, Select2ndOptionPins[0]))
	{
		K2NodeHelpers::EndExpandNode(this);
		return;
	}
	CompilerContext.MovePinLinksToIntermediate(*DefaultOptionPin, *Select2ndOptionPins[1]);

	// Link 2nd Select and outer
	CompilerContext.MovePinLinksToIntermediate(*ReturnValuePin, *Select2ndReturnValuePin);

	K2NodeHelpers::EndExpandNode(this);
}

bool UK2Node_MultiConditionalSelect::IsConnectionDisallowed(
	const UEdGraphPin* MyPin, const UEdGraphPin* OtherPin, FString& OutReason) const
{
	if (OtherPin && (OtherPin->PinType.PinCategory == UEdGraphSchema_K2::PC_Exec))
	{
		OutReason = LOCTEXT("ExecConnectionDisallowd", "Can't connect with Exec pin.").ToString();
		return true;
	}

	return Super::IsConnectionDisallowed(MyPin, OtherPin, OutReason);
}

void UK2Node_MultiConditionalSelect::CreateDefaultOptionPin()
{
	FCreatePinParams Params;
	Params.Index = 0;
	UEdGraphPin* DefaultOptionPin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Wildcard, DefaultOptionPinName, Params);
}

void UK2Node_MultiConditionalSelect::CreateReturnValuePin()
{
	int N = GetCasePinCount();

	FCreatePinParams Params;
	Params.Index = 2 * N + 1;
	UEdGraphPin* DefaultOptionPin = CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Wildcard, ReturnValueOptionPinName, Params);
}

UEdGraphPin* UK2Node_MultiConditionalSelect::GetDefaultOptionPin() const
{
	return FindPin(DefaultOptionPinName);
}

UEdGraphPin* UK2Node_MultiConditionalSelect::GetReturnValuePin() const
{
	return FindPin(ReturnValueOptionPinName);
}

CasePinPair UK2Node_MultiConditionalSelect::AddCasePinPair(int32 CaseIndex)
{
	CasePinPair Pair;
	int N = GetCasePinCount();
	UEdGraphPin* DefaultOptionPin = GetDefaultOptionPin();

	{
		FCreatePinParams Params;
		Params.Index = 1 + CaseIndex;
		Pair.Key = CreatePin(
			EGPD_Input, UEdGraphSchema_K2::PC_Wildcard, *GetCasePinName(CaseKeyPinNamePrefix.ToString(), CaseIndex), Params);
		Pair.Key->PinFriendlyName =
			FText::AsCultureInvariant(GetCasePinFriendlyName(CaseKeyPinFriendlyNamePrefix.ToString(), CaseIndex));
		Pair.Key->PinType = DefaultOptionPin->PinType;
	}
	{
		FCreatePinParams Params;
		Params.Index = N + 2 + CaseIndex;
		Pair.Value = CreatePin(
			EGPD_Input, UEdGraphSchema_K2::PC_Boolean, *GetCasePinName(CaseValuePinNamePrefix.ToString(), CaseIndex), Params);
		Pair.Value->PinFriendlyName =
			FText::AsCultureInvariant(GetCasePinFriendlyName(CaseValuePinFriendlyNamePrefix.ToString(), CaseIndex));
	}

	return Pair;
}

#undef LOCTEXT_NAMESPACE
