name: Build and Package Plugin

on:
  workflow_dispatch:

defaults:
  run:
    shell: powershell

jobs:
  build-windows:
    name: Build for Windows (UE ${{ matrix.ue_version }})
    runs-on: self-hosted
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        ue_version: ['5.3', '5.4', '5.5', '5.6']

    steps:
    - name: Set Environment Variables
      run: |
        $UE_PATH = "F:\Epic Games\UE_${{ matrix.ue_version }}"
        $VS_PATH = "E:\VisualStudio\2022"
        echo "UE_PATH=$UE_PATH" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        echo "VS2022INSTALLDIR=$VS_PATH" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        Write-Host "Runner will use UE version ${{ matrix.ue_version }}"

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Cache UE Build Intermediates
      uses: actions/cache@v4
      id: cache-ue-build
      with:
        path: ${{ github.workspace }}/TempHostProject/Intermediate
        key: build-cache-${{ matrix.ue_version }}-${{ runner.os }}-${{ hashFiles('Source/**', '*.uplugin') }}
        restore-keys: |
          build-cache-${{ matrix.ue_version }}-${{ runner.os }}-

    - name: Build and Package Plugin
      run: ./.github/scripts/Build-Plugin.ps1 -EngineVersion ${{ matrix.ue_version }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: XTools-UE_${{ matrix.ue_version }}-Win64
        path: ${{ github.workspace }}/PackagedPlugin/XTools-UE_${{ matrix.ue_version }}-Win64
        
    - name: Upload UBT Log
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: ubt-log-UE_${{ matrix.ue_version }}
        path: ${{ github.workspace }}/ubt.log

  summary:
    if: always()
    needs: [build-windows]
    runs-on: self-hosted
    
    steps:
    - name: Build Summary
      run: |
        echo "## XTools Plugin Build Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "| Engine Version | Status | Artifact |" >> $GITHUB_STEP_SUMMARY
        echo "|---|---|---|" >> $GITHUB_STEP_SUMMARY

        $buildResult = '${{ needs.build-windows.result }}'
        $ue_version = '${{ matrix.ue_version }}'
        $artifact_name = "XTools-UE_${ue_version}-Win64"

        if ($buildResult -eq 'success') {
          echo "| **UE ${ue_version}** | :white_check_mark: Success | \`$artifact_name\` |" >> $GITHUB_STEP_SUMMARY
        } else {
          echo "| **UE ${ue_version}** | :x: Failed | N/A |" >> $GITHUB_STEP_SUMMARY
        }
